//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Model.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public int ID { get; set; }
        public int TableID { get; set; }
        public Nullable<int> PromotionID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> SetDate { get; set; }
        public Nullable<decimal> TotalMoney { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public int ShopID { get; set; }
    
        public virtual Promotion Promotion { get; set; }
        public virtual Table Table { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
