//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Model.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopUser
    {
        public int ID { get; set; }
        public Nullable<int> ShopID { get; set; }
        public int UserID { get; set; }
        public int RoleID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual User User { get; set; }
    }
}
